name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem are you trying to solve? What's your use case?
      placeholder: |
        I'm trying to...

        Currently, I have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        It would be great if...

        The command could...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area does this feature relate to?
      options:
        - New command
        - Existing command enhancement
        - New adapter (design tool)
        - Design tokens
        - Templates
        - Agents
        - Documentation
        - Installation / Setup
        - GSD integration
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or additional context
